### ISSUE TITLE
fails to hide remaining pixels

### ISSUE THREAD

**Issue by ghost** [ihameed/task-homie#1]
after enabling task homie, yes the taskbar is hidden and I have the settings set to autohide, there is still a 1px high white line at the bottom of my screen - any solutions
![image_of_issue](https://user-images.githubusercontent.com/62097862/154170056-12529c28-0c3d-4fa2-a80d-cc5f1a1fe0c7.png)

**Comment by ihameed** [comment]
What version of Windows are you using?

**Comment by ghost** [comment]
Windows 10

**Comment by ihameed** [comment]
I'll take a look when I have time.
